# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-17 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formadores', '0056_contrato_codigo_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
