# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-02 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_entregable_escencial'),
        ('vigencia2017', '0002_auto_20170802_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocontrato',
            name='diplomados',
            field=models.ManyToManyField(to='productos.Diplomado'),
        ),
    ]
