# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-08 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vigencia2017', '0004_auto_20170803_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMatriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='Vigencia 2017/Carga Matriz/Archivo')),
                ('resultado', models.FileField(blank=True, null=True, upload_to='Vigencia 2017/Carga Matriz/Resultado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='valorentregablevigencia2017',
            name='valor',
            field=models.FloatField(default=0, null=True),
        ),
    ]
