# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-16 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_region_departamentos'),
        ('productos', '0004_entregable_escencial'),
        ('vigencia2017', '0007_auto_20170816_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('retroalimentacion', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='Formatos Red/Vigencia 2017/')),
                ('archivo_retroalimentacion', models.FileField(blank=True, null=True, upload_to='Formatos Red/Vigencia 2017/Retroalimentacion/')),
                ('producto_final', models.BooleanField(default=False)),
                ('beneficiarios', models.ManyToManyField(blank=True, related_name='vigencia_2017_beneficiarios_red', to='vigencia2017.Beneficiario')),
                ('diplomado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vigencia_2017_diplomdo', to='productos.Diplomado')),
                ('evidencias', models.ManyToManyField(blank=True, related_name='vigencia_2017_evidencia_red', to='vigencia2017.Evidencia')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vigencia_2017_region', to='region.Region')),
            ],
        ),
    ]
