# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-17 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigencia2017', '0008_red'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='red',
            name='evidencias',
        ),
    ]
