# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-24 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigencia2017', '0009_remove_red_evidencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='evidencia',
            name='beneficiarios_pagados',
            field=models.ManyToManyField(related_name='vigencia_2017_beneficiarios_pagados', to='vigencia2017.Beneficiario'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='corte_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
