# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-24 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigencia2017', '0010_auto_20170824_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='Evidencias/Vigencia 2017/No Conectividad'),
        ),
        migrations.AddField(
            model_name='grupos',
            name='no_conectividad',
            field=models.BooleanField(default=False),
        ),
    ]
