# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-25 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vigencia2017', '0011_auto_20170824_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField()),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigencia2017.Beneficiario')),
            ],
        ),
        migrations.RemoveField(
            model_name='evidencia',
            name='beneficiarios_pagados',
        ),
        migrations.AddField(
            model_name='pago',
            name='evidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigencia2017.Evidencia'),
        ),
    ]
